[tool.poetry]
name = "hexdna"
version = "0.1.0"
description = ""
authors = ["Gobion <1312216+brokenshield@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
